### ISSUE TITLE
Leafmap tutorials hang without loading widgets

### ISSUE THREAD

**Issue by robbibt** [giswqs/leafmap#17] opened 2021-06-04 04:41 UTC
### Environment Information

-   leafmap version: '0.1.0'
-   ipyleaflet version: '0.13.6'
-   Python version: Python 3.6.9
-   Operating System: Jupyterlab version 2.2.9, Jupyterhub / Ubuntu 18.04 based container running on an amazon linux kernel 

### Description

The `01_leafmap_intro.ipynb` notebook hangs on the third cell, displaying only "Loading widget" without ever displaying a map:

![image](https://user-images.githubusercontent.com/17680388/120746280-37d2b000-c542-11eb-9ad7-ba660ab2825d.png)

### What I Did

Using the Digital Earth Australia Sandbox Jupyterhub environment (https://app.sandbox.dea.ga.gov.au/), I launched the `01_leafmap_intro.ipynb` notebook then ran the following cells:

```
!pip install leafmap

import leafmap

m = leafmap.Map()
m
```

(I have also attempted to run the `05_load_raster.ipynb` notebook and had the same issue at the final `Display the map` cell, with the notebook simply displaying only "Loading widget" without ever displaying the map)

**Comment by robbibt** [comment] 2021-06-04 05:17
Hmm, it looks like this issue is actually coming from installing `xarray_leaflet` a part of the `05_load_raster.ipynb` notebook. This updates our versions of `ipyleaflet` and `ipywidget` from
```
0.13.0
7.5.1
```
to 
```
0.13.6
7.6.3
```

Which then seems to break any interactive leaflet plotting ability.

**Comment by giswqs** [comment] 2021-06-04 13:18
Thanks for reporting. This seems to be an issue caused by ipyleaflet rather than leafmap. I just tested the Sandbox by upgrading ipyleaflet (`!pip install -U ipyleaflet`) before installing anything else (e.g., leafmap, xarray_leaflet), and I got the same `Loading widget` error. A similar issue was reported with the geemap package before (see https://github.com/giswqs/geemap/issues/31). However, it seems the previouly working solution no longer works. I am not sure what internal change ipyleaflet has made that's causing the issue. I would encourage you to report it on the ipyleaflet GitHub repository. 

As an alternative, you can try out the leafmap binder environments created using this [environment.yml](https://github.com/giswqs/leafmap/blob/master/environment.yml). 

- https://gishub.org/leafmap-pangeo
- https://gishub.org/leafmap-binder
- https://gishub.org/leafmap-lab

**Comment by giswqs** [comment] 2021-06-04 13:46
One workaround is to downgrade ipyleaflet back to 0.13.0 (`!pip install ipyleaflet==0.13.0`) after installing leafmap. The map can be displayed correctly. However, the toolbar icons do not show up, but they still work. 

![](https://i.imgur.com/jZ8JfKd.png)

**Comment by giswqs** [comment] 2021-06-14 16:57
I am closing this issue for now as this requires a fix by the upstream ipyleaflet. Feel free to open an issue on the ipyleaflet GitHub repo https://github.com/jupyter-widgets/ipyleaflet/issues

**Closed by giswqs** 2021-06-14 16:57 UTC
Labels: bug
